export class User {
  id: string;
  uuid: string;
  name: string;
  email: string;
  role: number;
  gender: string;
  avatar: string;
  currency: string;
  timezone: string;
  language: string;
  nationality: string;
  country_id: number;
  region_id: number;
  city_id: number;
  phone: string;
  date_of_birth: string;
  locale: Date;
  card_number: string;
  customer_count?: number;
  demo?: number;
  expires_at?: string;
  plan_id?: string;
  plan_name?: string;
  available_points?: number;
  balance?: number;
  verification_code?: string;
  email_verified_at?: string;
}
